name: built_graphql
description: >
  Using built_value to deserialize GraphQL JSON responses. 
  The package provides generic classes to deal with the fix format of the GraphQL response and errors.
version: 1.0.1
homepage: https://www.github.com/dtengeri/built_graphql
author: dtengeri <dtengeri@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.3.0
  pedantic: ^1.0.0
  test: ^1.0.0
